FROM node:24-slim

RUN apt update && \
    apt-get update -y && \
    apt-get install -y openssl

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

WORKDIR /platform-api-ts

COPY package.json pnpm-lock.yaml .env.development ./

COPY . .

RUN pnpm install --frozen-lockfile

EXPOSE 3333

CMD ["pnpm", "dev"]
