FROM node:24-slim

RUN apt update

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

WORKDIR /platform-api-ts

COPY package.json pnpm-lock.yaml ./

RUN pnpm install

COPY . .

EXPOSE 3333

CMD ["pnpm", "dev"]
