services:
    postgres-db:
        image: postgres
        container_name: postgres-db
        ports:
            - 5431:5432
        env_file:
            - ./platform-api-ts/.env.dev

    platform-api-python:
        depends_on:
            - postgres-db
        build:
            context: ./platform-api-python
            dockerfile: Dockerfile.dev
        container_name: platform-api-python
        ports:
            - 8000:8000
        environment:
            - PYTHONDONTWRITEBYTECODE=1
            - PYTHONUNBUFFERED=1
        develop:
            watch:
                - action: sync+restart
                  path: ./platform-api-python
                  target: /platform-api-python
                  ignore:
                      - ".venv"
                      - "__pycache__"
                      - "*.pyc"
                      - "*.pyo"
                      - "*.pyd"
        env_file:
            - ./platform-api-python/.env.dev

    platform-api-ts:
        depends_on:
            - postgres-db
            - platform-api-python
        build:
            context: ./platform-api-ts
            dockerfile: Dockerfile.dev
        container_name: platform-api-ts
        ports:
            - 3333:3333
        develop:
            watch:
                - action: sync+restart
                  path: ./platform-api-ts
                  target: /platform-api-ts
                  ignore:
                      - node_modules
                      - dist
                      - .git
                      - .vscode
                      - .DS_Store
        env_file:
            - ./platform-api-ts/.env.dev

    platform-webapp:
        depends_on:
            - platform-api-ts
        build:
            context: ./platform-webapp
            dockerfile: Dockerfile.dev
        container_name: platform-webapp
        ports:
            - 3000:3000
        develop:
            watch:
                - action: sync+restart
                  path: ./platform-webapp
                  target: /platform-webapp
                  ignore:
                      - node_modules
                      - dist
                      - .git
                      - .vscode
                      - .DS_Store
        env_file:
            - ./platform-webapp/.env.dev
