services:
    platform-api-python:
        build:
            context: ./platform-api-python
            dockerfile: Dockerfile
        container_name: platform-api-python
        volumes:
            - ./platform-api-python:/app
            - platform_api_python_venv:/app/.venv
        ports:
            - 8000:8000
        environment:
            - PYTHONDONTWRITEBYTECODE=1
            - PYTHONUNBUFFERED=1
        env_file:
            - ./platform-api-python/.env.prod

    platform-api-ts:
        build:
            context: ./platform-api-ts
            dockerfile: Dockerfile
        container_name: platform-api-ts
        volumes:
            - ./platform-api-ts:/app
            - platform_api_ts_node_modules:/app/node_modules
        ports:
            - 3333:3333
        env_file:
            - ./platform-api-ts/.env.prod

    platform-webapp:
        build:
            context: ./platform-webapp
            dockerfile: Dockerfile
        container_name: platform-webapp
        volumes:
            - ./platform-webapp:/app
            - webapp_node_modules:/app/node_modules
        ports:
            - 3000:3000
        env_file:
            - ./platform-webapp/.env.prod

volumes:
    platform_api_python_venv:
    platform_api_ts_node_modules:
    webapp_node_modules:
