services:
    postgres-db:
        image: pgvector/pgvector:pg17
        container_name: postgres-db
        ports:
            - "5431:5432"
        env_file:
            - ./platform-api-ts/.env.development
        volumes:
            - postgres_data:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        depends_on:
            - postgres-db
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - "5050:80"

    platform-api-python:
        build:
            context: ./platform-api-python
            dockerfile: Dockerfile.dev
        container_name: platform-api-python
        ports:
            - "8000:8000"
        env_file:
            - ./platform-api-python/.env.development
        depends_on:
            - postgres-db
        develop:
            watch:
                - action: sync+restart
                  target: /platform-api-python
                  path: ./platform-api-python
                  ignore:
                      - .venv
                      - .git

    platform-api-ts:
        build:
            context: ./platform-api-ts
            dockerfile: Dockerfile.dev
        container_name: platform-api-ts
        ports:
            - "3333:3333"
        env_file:
            - ./platform-api-ts/.env.development
        depends_on:
            - postgres-db
        develop:
            watch:
                - action: sync+restart
                  target: /platform-api-ts
                  path: ./platform-api-ts
                  ignore:
                      - node_modules
                      - .git

    platform-webapp:
        build:
            context: ./platform-webapp
            dockerfile: Dockerfile.dev
        container_name: platform-webapp
        ports:
            - "5173:5173"
        env_file:
            - ./platform-webapp/.env.development
        depends_on:
            - platform-api-ts
        develop:
            watch:
                - action: sync+restart
                  target: /platform-webapp
                  path: ./platform-webapp
                  ignore:
                      - node_modules
                      - .git

volumes:
    postgres_data:
