services:
    platform-api-python:
        build:
            context: ./platform-api-python
            dockerfile: Dockerfile.dev
        container_name: platform-api-python
        ports:
            - 8000:8000
        develop:
            watch:
                - action: sync+restart
                  target: /platform-api-python
                  path: ./platform-api-python
                  ignore:
                      - .venv
                      - .git

    platform-api-ts:
        build:
            context: ./platform-api-ts
            dockerfile: Dockerfile.dev
        container_name: platform-api-ts
        ports:
            - 3333:3333
        develop:
            watch:
                - action: sync+restart
                  target: /platform-api-ts
                  path: ./platform-api-ts
                  ignore:
                      - node_modules
                      - .git

    platform-webapp:
        build:
            context: ./platform-webapp
            dockerfile: Dockerfile.dev
        container_name: platform-webapp
        ports:
            - 3000:3000
        develop:
            watch:
                - action: sync+restart
                  target: /platform-webapp
                  path: ./platform-webapp
                  ignore:
                      - node_modules
                      - .git

volumes:
    postgres_data:
